---
- name: Collect "show inventory" from IOS devices
  hosts: ios_switches
  gather_facts: no
  tasks:
    - name: Run "show inventory"
      ios_command:
        commands:
          - show inventory
      register: inventory_output

    - name: Print inventory output
      debug:
        var: inventory_output.stdout_lines

